---
name: Release

on:
  workflow_dispatch:
  
jobs:
  setup:
    name: Setup
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup VS2019
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Download and Extract Skia
        if: false
        run: |
          Write-Output "Get Location"
          Get-Location
          Write-Output "New Directory"
          New-Item -ItemType Directory -Path skia
          Write-Output "Download Zip"
          Invoke-WebRequest -Uri https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x64.zip -OutFile skia\Skia-Windows-Release-x64.zip
          Write-Output "Expand Archive"
          Expand-Archive -Path skia\Skia-Windows-Release-x64.zip
          Write-Output "Get file listing"
          Get-ChildItem -Path skia

      - name: Download and Extract Skia
        shell: bash
        run: |
          echo "Get Location"
          pwd
          echo "New Directory"
          mkdir skia
          echo "Download Zip"
          cd skia
          curl https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x64.zip
          echo "Expand Archive"
          unzip Skia-Windows-Release-x64.zip
          echo "List Files"
          ls -alh
          cd ..

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Make
        if: false
        run: |
          New-Item -ItemType Directory -Path build
          Set-Location -Path build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=..\skia -DSKIA_LIBRARY_DIR=..\skia\out\Release-x64 -DSKIA_LIBRARY=..\skia\out\Release-x64\skia.lib -G Ninja ..
          ninja aseprite
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Aseprite-Windows.exe
          path: build/bin/aseprite.exe
          if-no-files-found: error
