---
name: Release

on:
  workflow_dispatch:
  
jobs:
  setup:
    name: Setup
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup VS2019
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Download and Extract Skia
        shell: bash
        run: |
          echo "Get Location"
          pwd
          echo "New Directory"
          mkdir skia
          echo "Download Zip"
          cd skia
          curl -L https://github.com/aseprite/skia/releases/download/m81-b607b32047/Skia-Windows-Release-x64.zip -o Skia-Windows-Release-x64.zip
          echo "Expand Archive"
          unzip Skia-Windows-Release-x64.zip
          echo "List Files"
          ls -alh
          cd ..

      #- name: Set up CMake and Ninja
      #uses: lukka/get-cmake@latest

      - name: Vars
        run: |
          Write-Output "HOME: $($HOME)"
          Write-Output "WORKSPACE: $($env:GITHUB_WORKSPACE)"

      - name: Set up Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: Make
        shell: cmd
        run: |
          mkdir build
          cd build
          set CC=cl
          cmake -DCMAKE_IGNORE_PATH="C:/Strawberry/c/bin;C:/ProgramData/chocolatey/bin" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR="$($env:GITHUB_WORKSPACE)\skia" -DSKIA_LIBRARY_DIR="$($env:GITHUB_WORKSPACE)\skia\out\Release-x64" -DSKIA_LIBRARY="$($env:GITHUB_WORKSPACE)\skia\out\Release-x64\skia.lib" -G Ninja ..
          ninja aseprite
     
      - name: Output logs
        shell: bash
        run: |
          echo "CMakeOutput.log"
          cat build/CMakeFiles/CMakeOutput.log
          echo "CMakeError.log"
          cat build/CMakeFiles/CMakeError.log 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Aseprite-Windows.exe
          path: build/bin/aseprite.exe
          if-no-files-found: error
