---
name: Release

on:
  workflow_dispatch:
  
jobs:
  setup:
    name: Setup
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Test step
        run: |
          Write-Output "Test"
          Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools"

        - name: Setup VS2019
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Download and Extract Skia
        run: |
          Get-Location
          New-Item -ItemType Directory -Path skia
          Invoke-WebRequest -Uri https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x64.zip -OutFile skia\Skia-Windows-Release-x64.zip
          Expand-Archive -Path skia\Skia-Windows-Release-x64.zip
          Get-ChildItem -Path skia

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Make
        run: |
          New-Item -ItemType Directory -Path build
          Set-Location -Path build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=..\skia -DSKIA_LIBRARY_DIR=..\skia\out\Release-x64 -DSKIA_LIBRARY=..\skia\out\Release-x64\skia.lib -G Ninja ..
          ninja aseprite
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Aseprite-Windows.exe
          path: build/bin/aseprite.exe
          if-no-files-found: error
